# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#  parameter_name: value

services:
    locationsService:
        class: AppBundle\Service\Service
        arguments: ["@httpClient", "@responseParser"]

    httpClient:
        class: AppBundle\HttpClient\GuzzleAdapter
        arguments: ["@guzzleClient"]

    guzzleClient:
        class: GuzzleHttp\Client

    responseParser:
        class: AppBundle\Service\ResponseParser
